apiVersion: v1
version: 1.0.0
description: Installs the CRDs for Windows GMSA.
name: rancher-windows-gmsa-crd
type: application
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-windows-gmsa-system
  catalog.cattle.io/release-name: rancher-windows-gmsa-crd
